In [1]:
import pandas as pd

Here we import pandas as pd

In [2]:
data = pd.read_csv(r'C:\Users\Kaushik Tripathi\Desktop\FYP - IDA\DATA SET\WB_IDS_WIDEF.csv')

In [3]:
data.head(5)
data.shape
data.columns
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 366193 entries, 0 to 366192
Data columns (total 84 columns):
 #   Column                  Non-Null Count   Dtype
---  ------                  --------------   -----
 0   FREQ                    366193 non-null  object
 1   FREQ_LABEL              366193 non-null  object
 2   REF_AREA                366193 non-null  object
 3   REF_AREA_LABEL          366193 non-null  object
 4   INDICATOR               366193 non-null  object
 5   INDICATOR_LABEL         366193 non-null  object
 6   UNIT_MEASURE            366193 non-null  object
 7   UNIT_MEASURE_LABEL      366193 non-null  object
 8   COMP_BREAKDOWN_1        366193 non-null  object
 9   COMP_BREAKDOWN_1_LABEL  366193 non-null  object
 10  COMP_BREAKDOWN_2        366193 non-null  object
 11  COMP_BREAKDOWN_2_LABEL  366193 non-null  object
 12  COMP_BREAKDOWN_3        366193 non-null  object
 13  COMP_BREAKDOWN_3_LABEL  366193 non-null  object
 14  DATABASE_ID             366193 non-null  object
 15  DATABASE_ID_LABEL       366193 non-null  object
 16  UNIT_MULT               366193 non-null  int64
 17  UNIT_MULT_LABEL         366193 non-null  object
 18  OBS_STATUS              366193 non-null  object
 19  OBS_STATUS_LABEL        366193 non-null  object
 20  OBS_CONF                366193 non-null  object
 21  OBS_CONF_LABEL          366193 non-null  object
 22  1970                    171121 non-null  float64
 23  1971                    175127 non-null  float64
 24  1972                    178338 non-null  float64
 25  1973                    179949 non-null  float64
 26  1974                    181805 non-null  float64
 27  1975                    183764 non-null  float64
 28  1976                    185647 non-null  float64
 29  1977                    189371 non-null  float64
 30  1978                    194486 non-null  float64
 31  1979                    196308 non-null  float64
 32  1980                    199071 non-null  float64
 33  1981                    209894 non-null  float64
 34  1982                    211632 non-null  float64
 35  1983                    213465 non-null  float64
 36  1984                    216127 non-null  float64
 37  1985                    221116 non-null  float64
 38  1986                    221610 non-null  float64
 39  1987                    221003 non-null  float64
 40  1988                    221296 non-null  float64
 41  1989                    251889 non-null  float64
 42  1990                    250987 non-null  float64
 43  1991                    252976 non-null  float64
 44  1992                    264762 non-null  float64
 45  1993                    273530 non-null  float64
 46  1994                    276527 non-null  float64
 47  1995                    276835 non-null  float64
 48  1996                    276934 non-null  float64
 49  1997                    275813 non-null  float64
 50  1998                    276619 non-null  float64
 51  1999                    280362 non-null  float64
 52  2000                    279464 non-null  float64
 53  2001                    276207 non-null  float64
 54  2002                    274423 non-null  float64
 55  2003                    274103 non-null  float64
 56  2004                    275159 non-null  float64
 57  2005                    274508 non-null  float64
 58  2006                    276720 non-null  float64
 59  2007                    276043 non-null  float64
 60  2008                    276717 non-null  float64
 61  2009                    276917 non-null  float64
 62  2010                    276960 non-null  float64
 63  2011                    275976 non-null  float64
 64  2012                    276035 non-null  float64
 65  2013                    276232 non-null  float64
 66  2014                    281197 non-null  float64
 67  2015                    281345 non-null  float64
 68  2016                    280415 non-null  float64
 69  2017                    280653 non-null  float64
 70  2018                    280984 non-null  float64
 71  2019                    281831 non-null  float64
 72  2020                    283769 non-null  float64
 73  2021                    284380 non-null  float64
 74  2022                    283990 non-null  float64
 75  2023                    285173 non-null  float64
 76  2024                    12084 non-null   float64
 77  2025                    11392 non-null   float64
 78  2026                    10900 non-null   float64
 79  2027                    10571 non-null   float64
 80  2028                    10104 non-null   float64
 81  2029                    9477 non-null    float64
 82  2030                    9116 non-null    float64
 83  2031                    8650 non-null    float64
dtypes: float64(62), int64(1), object(21)
memory usage: 234.7+ MB

Read our main dataset which we downloaded

In [4]:
for column in data.columns:
    print (column,data[column].nunique())

FREQ 1
FREQ_LABEL 1
REF_AREA 134
REF_AREA_LABEL 134
INDICATOR 102
INDICATOR_LABEL 102
UNIT_MEASURE 7
UNIT_MEASURE_LABEL 7
COMP_BREAKDOWN_1 303
COMP_BREAKDOWN_1_LABEL 303
COMP_BREAKDOWN_2 6
COMP_BREAKDOWN_2_LABEL 6
COMP_BREAKDOWN_3 5
COMP_BREAKDOWN_3_LABEL 5
DATABASE_ID 1
DATABASE_ID_LABEL 1
UNIT_MULT 1
UNIT_MULT_LABEL 1
OBS_STATUS 1
OBS_STATUS_LABEL 1
OBS_CONF 1
OBS_CONF_LABEL 1
1970 13986
1971 15015
1972 16029
1973 17335
1974 18642
1975 19892
1976 21609
1977 23327
1978 24835
1979 26063
1980 27670
1981 29281
1982 30728
1983 31922
1984 32576
1985 33137
1986 33625
1987 33865
1988 34205
1989 42817
1990 42875
1991 42687
1992 42754
1993 42585
1994 43052
1995 42754
1996 42369
1997 41829
1998 41185
1999 40995
2000 40969
2001 41025
2002 40074
2003 39166
2004 38621
2005 37635
2006 36835
2007 35611
2008 35436
2009 34921
2010 34892
2011 33837
2012 33317
2013 33522
2014 32999
2015 32907
2016 32910
2017 33144
2018 33199
2019 33071
2020 34206
2021 33832
2022 32961
2023 32893
2024 4741
2025 4551
2026 4352
2027 4186
2028 4020
2029 3778
2030 3620
2031 3449

Here we start our data cleaning process where we clean our dataset which contain only one type of unique values

In [5]:
non_unique_list = []
for column in data.columns:
    print (column,data[column].nunique())
    if data[column].nunique() <2:
        non_unique_list.append(column)

FREQ 1
FREQ_LABEL 1
REF_AREA 134
REF_AREA_LABEL 134
INDICATOR 102
INDICATOR_LABEL 102
UNIT_MEASURE 7
UNIT_MEASURE_LABEL 7
COMP_BREAKDOWN_1 303
COMP_BREAKDOWN_1_LABEL 303
COMP_BREAKDOWN_2 6
COMP_BREAKDOWN_2_LABEL 6
COMP_BREAKDOWN_3 5
COMP_BREAKDOWN_3_LABEL 5
DATABASE_ID 1
DATABASE_ID_LABEL 1
UNIT_MULT 1
UNIT_MULT_LABEL 1
OBS_STATUS 1
OBS_STATUS_LABEL 1
OBS_CONF 1
OBS_CONF_LABEL 1
1970 13986
1971 15015
1972 16029
1973 17335
1974 18642
1975 19892
1976 21609
1977 23327
1978 24835
1979 26063
1980 27670
1981 29281
1982 30728
1983 31922
1984 32576
1985 33137
1986 33625
1987 33865
1988 34205
1989 42817
1990 42875
1991 42687
1992 42754
1993 42585
1994 43052
1995 42754
1996 42369
1997 41829
1998 41185
1999 40995
2000 40969
2001 41025
2002 40074
2003 39166
2004 38621
2005 37635
2006 36835
2007 35611
2008 35436
2009 34921
2010 34892
2011 33837
2012 33317
2013 33522
2014 32999
2015 32907
2016 32910
2017 33144
2018 33199
2019 33071
2020 34206
2021 33832
2022 32961
2023 32893
2024 4741
2025 4551
2026 4352
2027 4186
2028 4020
2029 3778
2030 3620
2031 3449

Here we created a list which contains non unique values columns so we can directly drop the whole columns

In [6]:
data.drop(columns= non_unique_list, inplace= True)

Here we drop the non unique values

In [7]:
data.isnull().sum().reset_index()

              index       0
0          REF_AREA       0
1    REF_AREA_LABEL       0
2         INDICATOR       0
3   INDICATOR_LABEL       0
4      UNIT_MEASURE       0
..              ...     ...
69             2027  355622
70             2028  356089
71             2029  356716
72             2030  357077
73             2031  357543

[74 rows x 2 columns]

Here we reset the index value of columns

In [8]:
columns = data.columns
id_vars = columns[:12]
value_vars = columns[12:]

print(id_vars)
print(value_vars)

Index(['REF_AREA', 'REF_AREA_LABEL', 'INDICATOR', 'INDICATOR_LABEL',
       'UNIT_MEASURE', 'UNIT_MEASURE_LABEL', 'COMP_BREAKDOWN_1',
       'COMP_BREAKDOWN_1_LABEL', 'COMP_BREAKDOWN_2', 'COMP_BREAKDOWN_2_LABEL',
       'COMP_BREAKDOWN_3', 'COMP_BREAKDOWN_3_LABEL'],
      dtype='object')
Index(['1970', '1971', '1972', '1973', '1974', '1975', '1976', '1977', '1978',
       '1979', '1980', '1981', '1982', '1983', '1984', '1985', '1986', '1987',
       '1988', '1989', '1990', '1991', '1992', '1993', '1994', '1995', '1996',
       '1997', '1998', '1999', '2000', '2001', '2002', '2003', '2004', '2005',
       '2006', '2007', '2008', '2009', '2010', '2011', '2012', '2013', '2014',
       '2015', '2016', '2017', '2018', '2019', '2020', '2021', '2022', '2023',
       '2024', '2025', '2026', '2027', '2028', '2029', '2030', '2031'],
      dtype='object')

Here we basically seperate out variables columns and values columns

In [9]:
df_All = pd.melt(data,
    id_vars= id_vars,
    value_vars= value_vars,
    var_name='Year',
    value_name='Value'

)
print (df_All)

         REF_AREA REF_AREA_LABEL                 INDICATOR  \
0             AFG    Afghanistan     WB_IDS_BN_CAB_XOKA_CD
1             AFG    Afghanistan  WB_IDS_BX_GRT_EXTA_CD_DT
2             AFG    Afghanistan  WB_IDS_BX_GRT_TECH_CD_DT
3             AFG    Afghanistan  WB_IDS_BX_KLT_DINV_CD_DT
4             AFG    Afghanistan  WB_IDS_BX_KLT_DREM_CD_DT
...           ...            ...                       ...
22703961      ZWE       Zimbabwe             WB_IDS_FI_RES
22703962      ZWE       Zimbabwe          WB_IDS_FI_RES_DT
22703963      ZWE       Zimbabwe          WB_IDS_FI_RES_MO
22703964      ZWE       Zimbabwe     WB_IDS_NY_GNP_MKTP_CD
22703965      ZWE       Zimbabwe        WB_IDS_SP_POP_TOTL

                                            INDICATOR_LABEL UNIT_MEASURE  \
0                                   Current account balance          USD
1                   Grants, excluding technical cooperation          USD
2                              Technical cooperation grants          USD
3         Foreign direct investment, net inflows in repo...          USD
4                                     Primary income on FDI          USD
...                                                     ...          ...
22703961                     Total reserves (includes gold)          USD
22703962                                     Total reserves    PT_DB_EXT
22703963                Total reserves in months of imports            M
22703964                                                GNI          USD
22703965                                  Population, total        COUNT

                   UNIT_MEASURE_LABEL             COMP_BREAKDOWN_1  \
0                          US dollars  WB_IDS_COUNTERPART_AREA_WLD
1                          US dollars  WB_IDS_COUNTERPART_AREA_WLD
2                          US dollars  WB_IDS_COUNTERPART_AREA_WLD
3                          US dollars  WB_IDS_COUNTERPART_AREA_WLD
4                          US dollars  WB_IDS_COUNTERPART_AREA_WLD
...                               ...                          ...
22703961                   US dollars  WB_IDS_COUNTERPART_AREA_WLD
22703962  Percentage of external debt  WB_IDS_COUNTERPART_AREA_WLD
22703963                       Months  WB_IDS_COUNTERPART_AREA_WLD
22703964                   US dollars  WB_IDS_COUNTERPART_AREA_WLD
22703965                        Count  WB_IDS_COUNTERPART_AREA_WLD

           COMP_BREAKDOWN_1_LABEL COMP_BREAKDOWN_2 COMP_BREAKDOWN_2_LABEL  \
0         Counterpart Area: World               _Z         Not Applicable
1         Counterpart Area: World               _Z         Not Applicable
2         Counterpart Area: World               _Z         Not Applicable
3         Counterpart Area: World               _Z         Not Applicable
4         Counterpart Area: World               _Z         Not Applicable
...                           ...              ...                    ...
22703961  Counterpart Area: World               _Z         Not Applicable
22703962  Counterpart Area: World               _Z         Not Applicable
22703963  Counterpart Area: World               _Z         Not Applicable
22703964  Counterpart Area: World               _Z         Not Applicable
22703965  Counterpart Area: World               _Z         Not Applicable

         COMP_BREAKDOWN_3 COMP_BREAKDOWN_3_LABEL  Year  Value
0                      _Z         Not Applicable  1970    NaN
1                      _Z         Not Applicable  1970    NaN
2                      _Z         Not Applicable  1970    NaN
3                      _Z         Not Applicable  1970    NaN
4                      _Z         Not Applicable  1970    NaN
...                   ...                    ...   ...    ...
22703961               _Z         Not Applicable  2031    NaN
22703962               _Z         Not Applicable  2031    NaN
22703963               _Z         Not Applicable  2031    NaN
22703964               _Z         Not Applicable  2031    NaN
22703965               _Z         Not Applicable  2031    NaN

[22703966 rows x 14 columns]

In [10]:
uniques = {}
for col in data.columns:
    uniques[col] = data[col].unique()

In [11]:
uniques

{'REF_AREA': array(['AFG', 'AGO', 'ALB', 'ARG', 'ARM', 'AZE', 'BDI', 'BEN', 'BFA',
        'BGD', 'BIH', 'BLR', 'BLZ', 'BOL', 'BRA', 'BTN', 'BWA', 'CAF',
        'CHN', 'CIV', 'CMR', 'COD', 'COG', 'COL', 'COM', 'CPV', 'CRI',
        'DJI', 'DMA', 'DOM', 'DZA', 'EAP', 'ECA', 'ECU', 'EGY', 'ERI',
        'ETH', 'FJI', 'GAB', 'GEO', 'GHA', 'GIN', 'GMB', 'GNB', 'GRD',
        'GTM', 'GUY', 'HND', 'HTI', 'IDA', 'IDN', 'IDX', 'IND', 'IRN',
        'IRQ', 'JAM', 'JOR', 'KAZ', 'KEN', 'KGZ', 'KHM', 'LAC', 'LAO',
        'LBN', 'LBR', 'LCA', 'LDC', 'LIC', 'LKA', 'LMC', 'LMY', 'LSO',
        'MAR', 'MDA', 'MDG', 'MDV', 'MEX', 'MIC', 'MKD', 'MLI', 'MMR',
        'MNA', 'MNE', 'MNG', 'MOZ', 'MRT', 'MUS', 'MWI', 'NER', 'NGA',
        'NIC', 'NPL', 'PAK', 'PER', 'PHL', 'PNG', 'PRY', 'RWA', 'SAS',
        'SDN', 'SEN', 'SLB', 'SLE', 'SLV', 'SOM', 'SRB', 'SSA', 'STP',
        'SUR', 'SWZ', 'SYR', 'TCD', 'TGO', 'THA', 'TJK', 'TKM', 'TLS',
        'TON', 'TUN', 'TUR', 'TZA', 'UGA', 'UKR', 'UMC', 'UZB', 'VCT',
        'VNM', 'VUT', 'WSM', 'XKX', 'YEM', 'ZAF', 'ZMB', 'ZWE'],
       dtype=object),
 'REF_AREA_LABEL': array(['Afghanistan', 'Angola', 'Albania', 'Argentina', 'Armenia',
        'Azerbaijan', 'Burundi', 'Benin', 'Burkina Faso', 'Bangladesh',
        'Bosnia and Herzegovina', 'Belarus', 'Belize', 'Bolivia', 'Brazil',
        'Bhutan', 'Botswana', 'Central African Republic', 'China',
        "Cote d'Ivoire", 'Cameroon', 'Congo, Dem. Rep.', 'Congo, Rep.',
        'Colombia', 'Comoros', 'Cabo Verde', 'Costa Rica', 'Djibouti',
        'Dominica', 'Dominican Republic', 'Algeria',
        'East Asia & Pacific (excluding high income)',
        'Europe & Central Asia (excluding high income)', 'Ecuador',
        'Egypt, Arab Rep.', 'Eritrea', 'Ethiopia', 'Fiji', 'Gabon',
        'Georgia', 'Ghana', 'Guinea', 'Gambia, The', 'Guinea-Bissau',
        'Grenada', 'Guatemala', 'Guyana', 'Honduras', 'Haiti', 'IDA total',
        'Indonesia', 'IDA only', 'India', 'Iran, Islamic Rep.', 'Iraq',
        'Jamaica', 'Jordan', 'Kazakhstan', 'Kenya', 'Kyrgyz Republic',
        'Cambodia', 'Latin America & Caribbean (excluding high income)',
        'Lao PDR', 'Lebanon', 'Liberia', 'St. Lucia',
        'Least developed countries: UN classification', 'Low income',
        'Sri Lanka', 'Lower middle income', 'Low & middle income',
        'Lesotho', 'Morocco', 'Moldova', 'Madagascar', 'Maldives',
        'Mexico', 'Middle income', 'North Macedonia', 'Mali', 'Myanmar',
        'Middle East & North Africa (excluding high income)', 'Montenegro',
        'Mongolia', 'Mozambique', 'Mauritania', 'Mauritius', 'Malawi',
        'Niger', 'Nigeria', 'Nicaragua', 'Nepal', 'Pakistan', 'Peru',
        'Philippines', 'Papua New Guinea', 'Paraguay', 'Rwanda',
        'South Asia', 'Sudan', 'Senegal', 'Solomon Islands',
        'Sierra Leone', 'El Salvador', 'Somalia', 'Serbia',
        'Sub-Saharan Africa (excluding high income)',
        'Sao Tome and Principe', 'Suriname', 'Eswatini',
        'Syrian Arab Republic', 'Chad', 'Togo', 'Thailand', 'Tajikistan',
        'Turkmenistan', 'Timor-Leste', 'Tonga', 'Tunisia', 'Turkiye',
        'Tanzania', 'Uganda', 'Ukraine', 'Upper middle income',
        'Uzbekistan', 'St. Vincent and the Grenadines', 'Viet Nam',
        'Vanuatu', 'Samoa', 'Kosovo', 'Yemen, Rep.', 'South Africa',
        'Zambia', 'Zimbabwe'], dtype=object),
 'INDICATOR': array(['WB_IDS_BN_CAB_XOKA_CD', 'WB_IDS_BX_GRT_EXTA_CD_DT',
        'WB_IDS_BX_GRT_TECH_CD_DT', 'WB_IDS_BX_KLT_DINV_CD_DT',
        'WB_IDS_BX_KLT_DREM_CD_DT', 'WB_IDS_BX_PEF_CD_DT',
        'WB_IDS_BX_TRF_PWKR_CD_DT', 'WB_IDS_DT_AMT_DIMF',
        'WB_IDS_DT_AMT_DLTF', 'WB_IDS_DT_AXA', 'WB_IDS_DT_AXF_DPPG',
        'WB_IDS_DT_BLT', 'WB_IDS_DT_BLT_GG', 'WB_IDS_DT_BLT_PS',
        'WB_IDS_DT_CUR_EURO', 'WB_IDS_DT_CUR_JYEN', 'WB_IDS_DT_CUR_MULC',
        'WB_IDS_DT_CUR_OTHC', 'WB_IDS_DT_CUR_SDRW', 'WB_IDS_DT_CUR_SWFR',
        'WB_IDS_DT_CUR_UKPS', 'WB_IDS_DT_CUR_USDL', 'WB_IDS_DT_DFR_DPPG',
        'WB_IDS_DT_DIS', 'WB_IDS_DT_DIS_DIMF', 'WB_IDS_DT_DIS_DLTF',
        'WB_IDS_DT_DIS_IDAG', 'WB_IDS_DT_DOD', 'WB_IDS_DT_DOD_C',
        'WB_IDS_DT_DOD_DECT_CD_CG', 'WB_IDS_DT_DOD_DECT_PC',
        'WB_IDS_DT_DOD_DIMF', 'WB_IDS_DT_DOD_DSDR', 'WB_IDS_DT_DOD_DSTC',
        'WB_IDS_DT_DOD_MDRI', 'WB_IDS_DT_DOD_MLAT', 'WB_IDS_DT_DOD_PUBS',
        'WB_IDS_DT_DOD_PVLX', 'WB_IDS_DT_DOD_RSDL', 'WB_IDS_DT_DOD_VTOT',
        'WB_IDS_DT_DOD_ZS', 'WB_IDS_DT_DSB_DPPG', 'WB_IDS_DT_DSF_DPPG',
        'WB_IDS_DT_DXR_DPPG', 'WB_IDS_DT_GPA', 'WB_IDS_DT_GRE',
        'WB_IDS_DT_INR', 'WB_IDS_DT_INT_DIMF', 'WB_IDS_DT_IXA',
        'WB_IDS_DT_IXA_DLXF', 'WB_IDS_DT_IXA_DPPG_CD_CG',
        'WB_IDS_DT_IXF_DPPG', 'WB_IDS_DT_IXR_DPPG', 'WB_IDS_DT_MAT',
        'WB_IDS_DT_MIDA', 'WB_IDS_DT_MLT', 'WB_IDS_DT_MLT_GG',
        'WB_IDS_DT_MLT_PS', 'WB_IDS_DT_NFL_NIFC', 'WB_IDS_DT_PNGC',
        'WB_IDS_DT_TDS_DECT_EX', 'WB_IDS_DT_TDS_DIMF',
        'WB_IDS_DT_TDS_MLAT', 'WB_IDS_DT_TXR_DPPG', 'WB_IDS_DT_UND',
        'WB_IDS_FI_RES', 'WB_IDS_FI_RES_DT', 'WB_IDS_FI_RES_MO',
        'WB_IDS_NY_GNP_MKTP_CD', 'WB_IDS_SP_POP_TOTL', 'WB_IDS_DT_AMT',
        'WB_IDS_DT_AXR', 'WB_IDS_DT_BLT_OPS', 'WB_IDS_DT_BLT_PRVG',
        'WB_IDS_DT_COM', 'WB_IDS_DT_CUR_DMAK', 'WB_IDS_DT_CUR_FFRC',
        'WB_IDS_DT_GG', 'WB_IDS_DT_INT', 'WB_IDS_DT_IXR', 'WB_IDS_DT_MIBR',
        'WB_IDS_DT_NFFL', 'WB_IDS_DT_NFL', 'WB_IDS_DT_NTR',
        'WB_IDS_DT_OPS', 'WB_IDS_DT_PBND', 'WB_IDS_DT_PBND_GG',
        'WB_IDS_DT_PBND_PS', 'WB_IDS_DT_PCBK', 'WB_IDS_DT_PCBK_GG',
        'WB_IDS_DT_PCBK_OPS', 'WB_IDS_DT_PCBK_PRVG', 'WB_IDS_DT_PCBK_PS',
        'WB_IDS_DT_PPG', 'WB_IDS_DT_PRVG', 'WB_IDS_DT_PS', 'WB_IDS_DT_TDS',
        'WB_IDS_DT_PBND_OPS', 'WB_IDS_DT_PNGB', 'WB_IDS_DT_MLT_OPS',
        'WB_IDS_DT_PBND_PRVG', 'WB_IDS_DT_MLT_PRVG'], dtype=object),
 'INDICATOR_LABEL': array(['Current account balance',
        'Grants, excluding technical cooperation',
        'Technical cooperation grants',
        'Foreign direct investment, net inflows in reporting economy (DRS)',
        'Primary income on FDI', 'Portfolio investment, equity (DRS)',
        'Personal transfers and compensation of employees, received',
        'IMF repurchases',
        'Principal repayments on external debt, long-term + IMF',
        'Principal arrears creditors', 'Principal forgiven',
        'Public and publicly guaranteed, bilateral',
        'General Government Debt, bilateral',
        'Public sector debt, bilateral',
        'Currency composition of PPG debt, Euro (%)',
        'Currency composition of PPG debt, Japanese yen (%)',
        'Currency composition of PPG debt, Multiple currencies (%)',
        'Currency composition of PPG debt, all other currencies (%)',
        'Currency composition of PPG debt, SDR (%)',
        'Currency composition of PPG debt, Swiss franc (%)',
        'Currency composition of PPG debt, Pound sterling (%)',
        'Currency composition of PPG debt, U.S. dollars (%)',
        'Debt forgiveness or reduction', 'Disbursements on external debt',
        'IMF purchases', 'Disbursements on external debt, long-term + IMF',
        'IDA grants', 'External debt stocks',
        'External debt stocks, concessional',
        'Total change in external debt stocks',
        'Total external debt per capita', 'Use of IMF credit',
        'Use of IMF credit, SDR allocations', 'Short-term debt',
        'Debt forgiveness grants', 'Multilateral debt',
        'External debt stocks, long-term public sector (DOD)',
        'Present value of external debt',
        'Residual, debt stock-flow reconciliation',
        'External debt stocks, variable rate (DOD)', 'Concessional debt',
        'Debt buyback', 'Debt stock reduction', 'Debt stock rescheduled',
        'Average grace period on new external debt commitments',
        'Average grant element on new external debt commitments',
        'Average interest on new external debt commitments', 'IMF charges',
        'Interest arrears creditors', 'Interest arrears, long-term DOD',
        'Net change in interest arrears', 'Interest forgiven',
        'Interest rescheduled (capitalized)',
        'Average maturity on new external debt commitments',
        'Public and publicly guaranteed, IDA',
        'Public and publicly guaranteed, multilateral',
        'General Government Debt, multilateral',
        'Public sector debt, multilateral', 'IFC nonguaranteed',
        'Private non-guaranteed,commercial banks and other creditors',
        'Total debt service', 'IMF repurchases and charges',
        'Multilateral debt service', 'Total amount of debt rescheduled',
        'Undisbursed external debt creditors',
        'Total reserves (includes gold)', 'Total reserves',
        'Total reserves in months of imports', 'GNI', 'Population, total',
        'Principal repayments on external debt', 'Principal rescheduled',
        'Other public sector debt, bilateral',
        'Private Guaranteed by Public Sector debt, bilateral',
        'Commitments creditors',
        'Currency composition of PPG debt, Deutsche mark (%)',
        'Currency composition of PPG debt, French franc (%)',
        'General Government creditors',
        'Interest payments on external debt', 'Interest rescheduled',
        'Public and publicly guaranteed, IBRD', 'Net financial flows',
        'Net flows on external debt', 'Net transfers on external debt',
        'Other public sector creditors',
        'Public and publicly guaranteed, bonds',
        'General Government Debt, bonds', 'Public sector debt, bonds',
        'Public and publicly guaranteed, commercial banks',
        'General Government Debt, commercial banks',
        'Other public sector debt, commercial banks',
        'Private Guaranteed by Public Sector debt, commercial banks',
        'Public sector debt, commercial banks',
        'Public and publicly guaranteed creditors',
        'Private Guaranteed by Public Sector creditors',
        'Public sector creditors', 'Debt service on external debt',
        'Other public sector debt, bonds', 'Private non-guaranteed,bonds',
        'Other public sector debt, multilateral',
        'Private Guaranteed by Public Sector debt, bonds',
        'Private Guaranteed by Public Sector debt, multilateral'],
       dtype=object),
 'UNIT_MEASURE': array(['USD', 'PT', 'PT_DB_EXT', 'PT_GNI', 'YR', 'M', 'COUNT'],
       dtype=object),
 'UNIT_MEASURE_LABEL': array(['US dollars', 'Percentage', 'Percentage of external debt',
        'Percentage of GNI', 'Years', 'Months', 'Count'], dtype=object),
 'COMP_BREAKDOWN_1': array(['WB_IDS_COUNTERPART_AREA_WLD', 'WB_IDS_COUNTERPART_AREA_IMF',
        'WB_IDS_COUNTERPART_AREA_ADB', 'WB_IDS_COUNTERPART_AREA_BGR',
        'WB_IDS_COUNTERPART_AREA_FCW', 'WB_IDS_COUNTERPART_AREA_GFR',
        'WB_IDS_COUNTERPART_AREA_IDA', 'WB_IDS_COUNTERPART_AREA_IRQ',
        'WB_IDS_COUNTERPART_AREA_ISDB', 'WB_IDS_COUNTERPART_AREA_OPEC',
        'WB_IDS_COUNTERPART_AREA_RUS', 'WB_IDS_COUNTERPART_AREA_SAU',
        'WB_IDS_COUNTERPART_AREA_USA', 'WB_IDS_COUNTERPART_AREA_HRV',
        'WB_IDS_COUNTERPART_AREA_KWT', 'WB_IDS_COUNTERPART_AREA_CHN',
        'WB_IDS_COUNTERPART_AREA_DNK', 'WB_IDS_COUNTERPART_AREA_IRN',
        'WB_IDS_COUNTERPART_AREA_ITA', 'WB_IDS_COUNTERPART_AREA_AAIB',
        'WB_IDS_COUNTERPART_AREA_ABW', 'WB_IDS_COUNTERPART_AREA_ADF',
        'WB_IDS_COUNTERPART_AREA_AEB', 'WB_IDS_COUNTERPART_AREA_AFESD',
        'WB_IDS_COUNTERPART_AREA_AFG', 'WB_IDS_COUNTERPART_AREA_AFTAAC',
        'WB_IDS_COUNTERPART_AREA_AGO', 'WB_IDS_COUNTERPART_AREA_AIA',
        'WB_IDS_COUNTERPART_AREA_AIB', 'WB_IDS_COUNTERPART_AREA_AIIB',
        'WB_IDS_COUNTERPART_AREA_AL', 'WB_IDS_COUNTERPART_AREA_ALB',
        'WB_IDS_COUNTERPART_AREA_ALBA', 'WB_IDS_COUNTERPART_AREA_AMF',
        'WB_IDS_COUNTERPART_AREA_AND', 'WB_IDS_COUNTERPART_AREA_ANT',
        'WB_IDS_COUNTERPART_AREA_ARE', 'WB_IDS_COUNTERPART_AREA_ARG',
        'WB_IDS_COUNTERPART_AREA_ARM', 'WB_IDS_COUNTERPART_AREA_ATG',
        'WB_IDS_COUNTERPART_AREA_ATO', 'WB_IDS_COUNTERPART_AREA_AUS',
        'WB_IDS_COUNTERPART_AREA_AUT', 'WB_IDS_COUNTERPART_AREA_AZE',
        'WB_IDS_COUNTERPART_AREA_BADEA', 'WB_IDS_COUNTERPART_AREA_BCEAO',
        'WB_IDS_COUNTERPART_AREA_BCIE', 'WB_IDS_COUNTERPART_AREA_BDEAC',
        'WB_IDS_COUNTERPART_AREA_BDI', 'WB_IDS_COUNTERPART_AREA_BEL',
        'WB_IDS_COUNTERPART_AREA_BEN', 'WB_IDS_COUNTERPART_AREA_BFA',
        'WB_IDS_COUNTERPART_AREA_BGD', 'WB_IDS_COUNTERPART_AREA_BHR',
        'WB_IDS_COUNTERPART_AREA_BHS', 'WB_IDS_COUNTERPART_AREA_BIH',
        'WB_IDS_COUNTERPART_AREA_BIS', 'WB_IDS_COUNTERPART_AREA_BLADEX',
        'WB_IDS_COUNTERPART_AREA_BLR', 'WB_IDS_COUNTERPART_AREA_BLZ',
        'WB_IDS_COUNTERPART_AREA_BMU', 'WB_IDS_COUNTERPART_AREA_BND',
        'WB_IDS_COUNTERPART_AREA_BOAD', 'WB_IDS_COUNTERPART_AREA_BOL',
        'WB_IDS_COUNTERPART_AREA_BRA', 'WB_IDS_COUNTERPART_AREA_BRB',
        'WB_IDS_COUNTERPART_AREA_BRN', 'WB_IDS_COUNTERPART_AREA_BTN',
        'WB_IDS_COUNTERPART_AREA_BWA', 'WB_IDS_COUNTERPART_AREA_CAF',
        'WB_IDS_COUNTERPART_AREA_CAN', 'WB_IDS_COUNTERPART_AREA_CARICOM',
        'WB_IDS_COUNTERPART_AREA_CCAF', 'WB_IDS_COUNTERPART_AREA_CDB',
        'WB_IDS_COUNTERPART_AREA_CEMLA', 'WB_IDS_COUNTERPART_AREA_CHE',
        'WB_IDS_COUNTERPART_AREA_CHL', 'WB_IDS_COUNTERPART_AREA_CIV',
        'WB_IDS_COUNTERPART_AREA_CMR', 'WB_IDS_COUNTERPART_AREA_COD',
        'WB_IDS_COUNTERPART_AREA_COE', 'WB_IDS_COUNTERPART_AREA_COG',
        'WB_IDS_COUNTERPART_AREA_COL', 'WB_IDS_COUNTERPART_AREA_COLAC',
        'WB_IDS_COUNTERPART_AREA_COM', 'WB_IDS_COUNTERPART_AREA_CP',
        'WB_IDS_COUNTERPART_AREA_CPV', 'WB_IDS_COUNTERPART_AREA_CRI',
        'WB_IDS_COUNTERPART_AREA_CUB', 'WB_IDS_COUNTERPART_AREA_CYM',
        'WB_IDS_COUNTERPART_AREA_CYP', 'WB_IDS_COUNTERPART_AREA_CZCH',
        'WB_IDS_COUNTERPART_AREA_CZE', 'WB_IDS_COUNTERPART_AREA_DJI',
        'WB_IDS_COUNTERPART_AREA_DMA', 'WB_IDS_COUNTERPART_AREA_DOM',
        'WB_IDS_COUNTERPART_AREA_DZA', 'WB_IDS_COUNTERPART_AREA_EAC',
        'WB_IDS_COUNTERPART_AREA_EBRD', 'WB_IDS_COUNTERPART_AREA_EC',
        'WB_IDS_COUNTERPART_AREA_ECGLC', 'WB_IDS_COUNTERPART_AREA_ECOWAS',
        'WB_IDS_COUNTERPART_AREA_ECSC', 'WB_IDS_COUNTERPART_AREA_ECU',
        'WB_IDS_COUNTERPART_AREA_EDB', 'WB_IDS_COUNTERPART_AREA_EDF',
        'WB_IDS_COUNTERPART_AREA_EEC', 'WB_IDS_COUNTERPART_AREA_EFTA',
        'WB_IDS_COUNTERPART_AREA_EGY', 'WB_IDS_COUNTERPART_AREA_EIB',
        'WB_IDS_COUNTERPART_AREA_ERF', 'WB_IDS_COUNTERPART_AREA_ERI',
        'WB_IDS_COUNTERPART_AREA_ESF', 'WB_IDS_COUNTERPART_AREA_ESP',
        'WB_IDS_COUNTERPART_AREA_EST', 'WB_IDS_COUNTERPART_AREA_ETADB',
        'WB_IDS_COUNTERPART_AREA_ETH', 'WB_IDS_COUNTERPART_AREA_EURFM',
        'WB_IDS_COUNTERPART_AREA_EUU', 'WB_IDS_COUNTERPART_AREA_FAO',
        'WB_IDS_COUNTERPART_AREA_FHR', 'WB_IDS_COUNTERPART_AREA_FIN',
        'WB_IDS_COUNTERPART_AREA_FJI', 'WB_IDS_COUNTERPART_AREA_FLAR',
        'WB_IDS_COUNTERPART_AREA_FMS', 'WB_IDS_COUNTERPART_AREA_FONP',
        'WB_IDS_COUNTERPART_AREA_FRA', 'WB_IDS_COUNTERPART_AREA_GAB',
        'WB_IDS_COUNTERPART_AREA_GBR', 'WB_IDS_COUNTERPART_AREA_GDR',
        'WB_IDS_COUNTERPART_AREA_GEF', 'WB_IDS_COUNTERPART_AREA_GEO',
        'WB_IDS_COUNTERPART_AREA_GHA', 'WB_IDS_COUNTERPART_AREA_GIB',
        'WB_IDS_COUNTERPART_AREA_GIN', 'WB_IDS_COUNTERPART_AREA_GLP',
        'WB_IDS_COUNTERPART_AREA_GMB', 'WB_IDS_COUNTERPART_AREA_GNB',
        'WB_IDS_COUNTERPART_AREA_GNQ', 'WB_IDS_COUNTERPART_AREA_GRC',
        'WB_IDS_COUNTERPART_AREA_GRD', 'WB_IDS_COUNTERPART_AREA_GTM',
        'WB_IDS_COUNTERPART_AREA_GUM', 'WB_IDS_COUNTERPART_AREA_GUY',
        'WB_IDS_COUNTERPART_AREA_HKG', 'WB_IDS_COUNTERPART_AREA_HND',
        'WB_IDS_COUNTERPART_AREA_HTI', 'WB_IDS_COUNTERPART_AREA_HUN',
        'WB_IDS_COUNTERPART_AREA_IBFEC', 'WB_IDS_COUNTERPART_AREA_IBRD',
        'WB_IDS_COUNTERPART_AREA_ICO', 'WB_IDS_COUNTERPART_AREA_IDB',
        'WB_IDS_COUNTERPART_AREA_IDN', 'WB_IDS_COUNTERPART_AREA_IFC',
        'WB_IDS_COUNTERPART_AREA_IFFAD', 'WB_IDS_COUNTERPART_AREA_IIB',
        'WB_IDS_COUNTERPART_AREA_ILO', 'WB_IDS_COUNTERPART_AREA_IND',
        'WB_IDS_COUNTERPART_AREA_INSTRAW', 'WB_IDS_COUNTERPART_AREA_IRL',
        'WB_IDS_COUNTERPART_AREA_ISFD', 'WB_IDS_COUNTERPART_AREA_ISL',
        'WB_IDS_COUNTERPART_AREA_ISR', 'WB_IDS_COUNTERPART_AREA_JAM',
        'WB_IDS_COUNTERPART_AREA_JOR', 'WB_IDS_COUNTERPART_AREA_JPN',
        'WB_IDS_COUNTERPART_AREA_KAZ', 'WB_IDS_COUNTERPART_AREA_KEN',
        'WB_IDS_COUNTERPART_AREA_KGZ', 'WB_IDS_COUNTERPART_AREA_KHM',
        'WB_IDS_COUNTERPART_AREA_KIR', 'WB_IDS_COUNTERPART_AREA_KNA',
        'WB_IDS_COUNTERPART_AREA_KOR', 'WB_IDS_COUNTERPART_AREA_LAAD',
        'WB_IDS_COUNTERPART_AREA_LAO', 'WB_IDS_COUNTERPART_AREA_LBN',
        'WB_IDS_COUNTERPART_AREA_LBR', 'WB_IDS_COUNTERPART_AREA_LBY',
        'WB_IDS_COUNTERPART_AREA_LCA', 'WB_IDS_COUNTERPART_AREA_LKA',
        'WB_IDS_COUNTERPART_AREA_LSO', 'WB_IDS_COUNTERPART_AREA_LTU',
        'WB_IDS_COUNTERPART_AREA_LUX', 'WB_IDS_COUNTERPART_AREA_LVA',
        'WB_IDS_COUNTERPART_AREA_MAC', 'WB_IDS_COUNTERPART_AREA_MAR',
        'WB_IDS_COUNTERPART_AREA_MCO', 'WB_IDS_COUNTERPART_AREA_MDA',
        'WB_IDS_COUNTERPART_AREA_MDG', 'WB_IDS_COUNTERPART_AREA_MDV',
        'WB_IDS_COUNTERPART_AREA_MEX', 'WB_IDS_COUNTERPART_AREA_MIGA',
        'WB_IDS_COUNTERPART_AREA_MKD', 'WB_IDS_COUNTERPART_AREA_ML',
        'WB_IDS_COUNTERPART_AREA_MLI', 'WB_IDS_COUNTERPART_AREA_MLT',
        'WB_IDS_COUNTERPART_AREA_MMR', 'WB_IDS_COUNTERPART_AREA_MNE',
        'WB_IDS_COUNTERPART_AREA_MNG', 'WB_IDS_COUNTERPART_AREA_MOZ',
        'WB_IDS_COUNTERPART_AREA_MPF', 'WB_IDS_COUNTERPART_AREA_MRT',
        'WB_IDS_COUNTERPART_AREA_MUS', 'WB_IDS_COUNTERPART_AREA_MWI',
        'WB_IDS_COUNTERPART_AREA_MYS', 'WB_IDS_COUNTERPART_AREA_NAM',
        'WB_IDS_COUNTERPART_AREA_NCL', 'WB_IDS_COUNTERPART_AREA_NDB',
        'WB_IDS_COUNTERPART_AREA_NDF', 'WB_IDS_COUNTERPART_AREA_NEFCO',
        'WB_IDS_COUNTERPART_AREA_NER', 'WB_IDS_COUNTERPART_AREA_NGA',
        'WB_IDS_COUNTERPART_AREA_NIB', 'WB_IDS_COUNTERPART_AREA_NIC',
        'WB_IDS_COUNTERPART_AREA_NLD', 'WB_IDS_COUNTERPART_AREA_NOR',
        'WB_IDS_COUNTERPART_AREA_NPL', 'WB_IDS_COUNTERPART_AREA_NZL',
        'WB_IDS_COUNTERPART_AREA_OAPEC', 'WB_IDS_COUNTERPART_AREA_OMN',
        'WB_IDS_COUNTERPART_AREA_PAK', 'WB_IDS_COUNTERPART_AREA_PAN',
        'WB_IDS_COUNTERPART_AREA_PER', 'WB_IDS_COUNTERPART_AREA_PHL',
        'WB_IDS_COUNTERPART_AREA_PNG', 'WB_IDS_COUNTERPART_AREA_POL',
        'WB_IDS_COUNTERPART_AREA_PRI', 'WB_IDS_COUNTERPART_AREA_PRK',
        'WB_IDS_COUNTERPART_AREA_PRT', 'WB_IDS_COUNTERPART_AREA_PRY',
        'WB_IDS_COUNTERPART_AREA_PSS', 'WB_IDS_COUNTERPART_AREA_PYF',
        'WB_IDS_COUNTERPART_AREA_QAT', 'WB_IDS_COUNTERPART_AREA_REU',
        'WB_IDS_COUNTERPART_AREA_ROU', 'WB_IDS_COUNTERPART_AREA_RPTA',
        'WB_IDS_COUNTERPART_AREA_RPTC', 'WB_IDS_COUNTERPART_AREA_RWA',
        'WB_IDS_COUNTERPART_AREA_SADF', 'WB_IDS_COUNTERPART_AREA_SDN',
        'WB_IDS_COUNTERPART_AREA_SEN', 'WB_IDS_COUNTERPART_AREA_SGP',
        'WB_IDS_COUNTERPART_AREA_SLB', 'WB_IDS_COUNTERPART_AREA_SLE',
        'WB_IDS_COUNTERPART_AREA_SLV', 'WB_IDS_COUNTERPART_AREA_SOM',
        'WB_IDS_COUNTERPART_AREA_SRB', 'WB_IDS_COUNTERPART_AREA_SSR',
        'WB_IDS_COUNTERPART_AREA_STP', 'WB_IDS_COUNTERPART_AREA_SUR',
        'WB_IDS_COUNTERPART_AREA_SVK', 'WB_IDS_COUNTERPART_AREA_SVN',
        'WB_IDS_COUNTERPART_AREA_SWE', 'WB_IDS_COUNTERPART_AREA_SWZ',
        'WB_IDS_COUNTERPART_AREA_SYC', 'WB_IDS_COUNTERPART_AREA_SYR',
        'WB_IDS_COUNTERPART_AREA_TCD', 'WB_IDS_COUNTERPART_AREA_TDB',
        'WB_IDS_COUNTERPART_AREA_TGO', 'WB_IDS_COUNTERPART_AREA_THA',
        'WB_IDS_COUNTERPART_AREA_TJK', 'WB_IDS_COUNTERPART_AREA_TKM',
        'WB_IDS_COUNTERPART_AREA_TLS', 'WB_IDS_COUNTERPART_AREA_TON',
        'WB_IDS_COUNTERPART_AREA_TTO', 'WB_IDS_COUNTERPART_AREA_TUN',

In [12]:
uniques = pd.DataFrame(dict([(k, pd.Series(v)) for k,v in uniques.items()]))

In [13]:
columns = data.columns
id_vars = columns[:12]
value_vars = columns[12:]

print(id_vars)
print(value_vars)

Index(['REF_AREA', 'REF_AREA_LABEL', 'INDICATOR', 'INDICATOR_LABEL',
       'UNIT_MEASURE', 'UNIT_MEASURE_LABEL', 'COMP_BREAKDOWN_1',
       'COMP_BREAKDOWN_1_LABEL', 'COMP_BREAKDOWN_2', 'COMP_BREAKDOWN_2_LABEL',
       'COMP_BREAKDOWN_3', 'COMP_BREAKDOWN_3_LABEL'],
      dtype='object')
Index(['1970', '1971', '1972', '1973', '1974', '1975', '1976', '1977', '1978',
       '1979', '1980', '1981', '1982', '1983', '1984', '1985', '1986', '1987',
       '1988', '1989', '1990', '1991', '1992', '1993', '1994', '1995', '1996',
       '1997', '1998', '1999', '2000', '2001', '2002', '2003', '2004', '2005',
       '2006', '2007', '2008', '2009', '2010', '2011', '2012', '2013', '2014',
       '2015', '2016', '2017', '2018', '2019', '2020', '2021', '2022', '2023',
       '2024', '2025', '2026', '2027', '2028', '2029', '2030', '2031'],
      dtype='object')

In [14]:
df_melt = pd.melt(data,
    id_vars=id_vars,
    value_vars= value_vars,
    var_name='Year',
    value_name='Value'
)

In [15]:
df_melt['COMP_BREAKDOWN_1_LABEL'] = df_melt['COMP_BREAKDOWN_1_LABEL'].str.replace('Counterpart Area: ', '')

Counterpart Area is a common word which use in every records of columns COMP_BREAKDOWN_1_LABEL

In [16]:
df_melt.drop(columns=['INDICATOR' , 'UNIT_MEASURE' , 'COMP_BREAKDOWN_1' , 'COMP_BREAKDOWN_2' , 'COMP_BREAKDOWN_3', 'REF_AREA'], errors='ignore', inplace = True)

Here we drop unwanted columns in our dataset

In [17]:
df_melt.rename(columns ={"COMP_BREAKDOWN_1_LABEL" : "Counter_Part" , "COMP_BREAKDOWN_2_LABEL" : "Nature" , "COMP_BREAKDOWN_3_LABEL" : "Type"}, inplace =True)

In [34]:
df_All.shape

(22703966, 14)

Here we rename columns name according to our needs

In [18]:
df_melt.sample(5)

,REF_AREA_LABEL,INDICATOR_LABEL,UNIT_MEASURE_LABEL,Counter_Part,Nature,Type,Year,Value
12671506,Middle income,Debt buyback,US dollars,Viet Nam,Not Applicable,Not Applicable,2004,NaN
11580221,Mali,"Disbursements on external debt, long-term + IMF",US dollars,UN-Fund for Human Rights,Not Applicable,Not Applicable,2001,0.0
8677847,Nicaragua,"General Government Debt, bilateral",US dollars,Italy,Stock/Flow: Debt service payments,Concessional: Concessional,1993,NaN
19437314,Belize,Disbursements on external debt,US dollars,International Bank for Economic Cooperation (I...,Debtor Coverage: Private Guaranteed by Public ...,Not Applicable,2023,0.0
14883624,Middle East & North Africa (excluding high inc...,Total amount of debt rescheduled,US dollars,China,Not Applicable,Not Applicable,2010,NaN

Here is sample records of dataset which is clean and understandable

In [19]:
india_df = df_melt[df_melt['REF_AREA_LABEL'] == 'India']

Here we seperate out India data form dataset

In [37]:
india_df.sample(5)

,REF_AREA_LABEL,INDICATOR_LABEL,UNIT_MEASURE_LABEL,Counter_Part,Nature,Type,Year,Value
16986654,India,Average maturity on new external debt commitments,Years,Nordic Development Fund,Creditor Coverage: Private Creditors,Not Applicable,2016,0.0
22111130,India,"Currency composition of PPG debt, SDR (%)",Percentage,Serbia,Not Applicable,Not Applicable,2030,NaN
19182235,India,IMF purchases,US dollars,Entente Council,Not Applicable,Not Applicable,2022,0.0
7830295,India,IMF purchases,US dollars,Grenada,Not Applicable,Not Applicable,1991,0.0
16984463,India,"Currency composition of PPG debt, Swiss franc (%)",Percentage,Hong Kong,Not Applicable,Not Applicable,2016,0.0

In [38]:
india_df.shape

(213962, 8)

In [21]:
india_df.to_csv("IND.csv")

create csv file which contain India Dataset for furthur visulaization

In [22]:
China_df = df_melt[df_melt['REF_AREA_LABEL'] == 'China']

In [23]:
China_df.sample(5)

,REF_AREA_LABEL,INDICATOR_LABEL,UNIT_MEASURE_LABEL,Counter_Part,Nature,Type,Year,Value
14326088,China,IMF purchases,US dollars,Lao People's Democratic Rep.,Not Applicable,Not Applicable,2009,0.0
14692037,China,Disbursements on external debt,US dollars,Qatar,Debtor Coverage: Private Guaranteed by Public ...,Not Applicable,2010,0.0
12860636,China,"Currency composition of PPG debt, SDR (%)",Percentage,Argentina,Not Applicable,Not Applicable,2005,0.0
22017241,China,"Public sector debt, multilateral",US dollars,World,Stock/Flow: Debt service payments,Concessional: Concessional,2030,NaN
5171152,China,IMF purchases,US dollars,Switzerland,Not Applicable,Not Applicable,1984,0.0

In [39]:
China_df.shape

(156178, 8)

In [24]:
China_df.to_csv("CHI.csv")

In [25]:
Pakistan_df = df_melt[df_melt['REF_AREA_LABEL'] == 'Pakistan']

In [26]:
Pakistan_df.sample(5)

,REF_AREA_LABEL,INDICATOR_LABEL,UNIT_MEASURE_LABEL,Counter_Part,Nature,Type,Year,Value
630072,Pakistan,Total amount of debt rescheduled,US dollars,Plata Basin Financial Dev. Fund,Not Applicable,Not Applicable,1971,NaN
22233306,Pakistan,Disbursements on external debt,US dollars,UN-INSTRAW,Debtor Coverage: Private Guaranteed by Public ...,Not Applicable,2030,NaN
22600314,Pakistan,"External debt stocks, concessional",US dollars,Libya,Not Applicable,Not Applicable,2031,NaN
13446287,Pakistan,Net change in interest arrears,US dollars,Hungary,Not Applicable,Not Applicable,2006,0.0
11249011,Pakistan,Interest arrears creditors,US dollars,United Arab Emirates,Creditor Coverage: Private Creditors,Not Applicable,2000,NaN

In [40]:
Pakistan_df.shape

(203794, 8)

In [27]:
Pakistan_df.to_csv("Pak.csv")

In [28]:
NEP_df = df_melt[df_melt['REF_AREA_LABEL'] == 'Nepal']

In [29]:
NEP_df.sample(5)

,REF_AREA_LABEL,INDICATOR_LABEL,UNIT_MEASURE_LABEL,Counter_Part,Nature,Type,Year,Value
21498465,Nepal,Disbursements on external debt,US dollars,European Union,Debtor Coverage: Private Guaranteed by Public ...,Not Applicable,2028,NaN
20766413,Nepal,IMF purchases,US dollars,Haiti,Not Applicable,Not Applicable,2026,NaN
5020649,Nepal,"Use of IMF credit, SDR allocations",US dollars,World,Not Applicable,Not Applicable,1983,NaN
3555992,Nepal,"Residual, debt stock-flow reconciliation",US dollars,"Germany, Fed. Rep. of",Not Applicable,Not Applicable,1979,NaN
991605,Nepal,Disbursements on external debt,US dollars,Botswana,Debtor Coverage: Private Guaranteed by Public ...,Not Applicable,1972,0.0

In [41]:
NEP_df.shape

(121954, 8)

In [30]:
NEP_df.to_csv("NEP.csv")

In [31]:
BAN_df = df_melt[df_melt['REF_AREA_LABEL'] == 'Bangladesh']

In [32]:
BAN_df.sample(5)

,REF_AREA_LABEL,INDICATOR_LABEL,UNIT_MEASURE_LABEL,Counter_Part,Nature,Type,Year,Value
6979642,Bangladesh,"Currency composition of PPG debt, Multiple cur...",Percentage,France,Not Applicable,Not Applicable,1989,0.0
15402919,Bangladesh,IMF purchases,US dollars,Maldives,Not Applicable,Not Applicable,2012,0.0
6613925,Bangladesh,Disbursements on external debt,US dollars,Equatorial Guinea,Debtor Coverage: Private Guaranteed by Public ...,Not Applicable,1988,0.0
13206757,Bangladesh,Interest arrears creditors,US dollars,Hungary,Creditor Coverage: Private Creditors,Not Applicable,2006,NaN
21993409,Bangladesh,"Currency composition of PPG debt, Euro (%)",Percentage,Japan,Not Applicable,Not Applicable,2030,NaN

In [42]:
BAN_df.shape

(162750, 8)

In [33]:
BAN_df.to_csv("BAN.csv")